### PR TITLE
HTML5 Media time and Youtube/Vimeo tracking

### PR DESCRIPTION
**Pull request by fpzero**
Tracking HTML5 Media percentage and volume change.

Bug fixed - Youtube percentage wasn't working on Internet Explorer.

### CODE REVIEW

**Comment by eduardocereto** [comment]
Nice this is our very first pull request. I see some problems with it.

First I'd like to ask you guys to do pull requests to the develop branch. Unless it's a small fix to a very nasty bug. We're trying to keep master as stable as possible.

This is a fairly large update and it overwrite some changes I did to rename some variables like the poolMaps on yt tracker. 

So I'll try to review and merge back into our develop branch.

Obrigado amigos da digitalinc

**Comment by eduardocereto** [comment]
a20f0f9 looks very bad. I think it was implemented based on https://github.com/eduardocereto/GA-Code-Samples/blob/master/src/youtube.js which is not the same code as GAS. So I can't merge this one here. They are too distinct you better do the change again based on gas.

**Comment by eduardocereto** [comment]
I think that tracking tracking percentages on HTML5 media elements is a good addition, and brings it on par with youTube and Video. But I'm not so sure about volume changes. I discussed this here internally in Cardinal Path and we don't see much value on this feature. Can you guys come up with some good use cases for tracking volume changes?

**Comment by eduardocereto** [comment]
I see some problems with dd6cbe0.

The timeTriggers are stored globally but in theory the user could select a set of percentages for Video and a different set for Audio.

It also seems that once you start pooling the video for current times you never stop. Notice that when we see a 'pause' or 'finish' for youtube we stop pooling the video.

But you shouldn't bother we pool youtube player each X milliseconds because it's the only way. Vimeo provides an event 'playProgress' while the video is playing. Turns out that HTML5 also provides a native event called `timeupdate` which is supposed to fire at each 250ms. That should be enough for us. You can listen to this event and check if we need to fire percentages reached. Way easier than pooling the player.

I'll let you guys fix these issues and change this pull request. Please submit each of the features as a different pull request if you can. It makes it easier to merge them.

Here we have at least 3 new changes:
- A bug fix for Youtube on MSIE
- percentages tracking for HTML5 Media
- volume changes for HTML5 media.

And please do it against the develop branch, which will make merging way easier to me. 

But thanks anyway. This was a start.

**Comment by arosellisp** [comment]
I´ll look into the a20f0f9, thank you

**Pull request closed without merging**
