### PR TITLE
Added _gasTrackDoubleClick hook

### PR DESCRIPTION
**Pull request by tomfuertes**
Option to pull in /dc.js instead of /ga.js

### CODE REVIEW

**Comment by eduardocereto** [comment]
That is great. Thanks Tom. 

The only problem I see with that is that the gas.js file MUST be loaded after the tracking script in order for the dc.js file to be loaded using `_gasTrackDoubleClick`. There's nothing we can do about it, and I still want this feature in, so I guess the best we can do is put a warning in the readme about it.

I also try to avoid the word track as it's only present in functions that actualy send a hit to google Analytics. I'll change the name to `_gasSetRemarketing`

**Comment by eduardocereto** [comment]
It seems that this is not working for me. The code that loads the ga.js file runs before the hook is processed. We probably have to change it to delay the load of ga.js until all the _gas array has been processed.

http://jsbin.com/ahiluc/1/quiet

**Comment by igrigorik** [comment]
Any updates on this one? Would love to see it merged.

**Comment by nikosd** [comment]
I'm also interested in this. Can I help somehow?

**Comment by eduardocereto** [comment]
It won't be merged because it currently doesn't work the way it is. I'm working on some biggest changes so it will likely not be fixed in this version unless someone else is interested in owning this.

**Comment by nikosd** [comment]
I _may_ give it some time :)

**Comment by philippschneider** [comment]
any news on this? I would love to integrate dc.js since it gets not blocked by adblock anymore :-)

**Comment by DarrenCarterMD** [comment]
I'd love to see a solution here, too, since I use dc.js so that I can build remarketing lists in Analytics. I don't want to lose that feature to use GAS.

**Comment by rdonovan** [comment]
Another vote for this, this feature would be extremely useful.

**Comment by tomfuertes** [comment]
Per @eduardocereto above, there isn't really a way to do this that keeps with the async nature of the API. If you'd like to include dc.js the best thing to do is just find/replace the strings in the bottom of the file. Ping me if you're having trouble and I'll come back and post some actual built files.

**Comment by rdonovan** [comment]
Thanks for the response, I appreciate the clarification. Will give it a shot.

**Comment by BrianKatz** [comment]
The problem, IMHO, is that attempts to use dc.js within gas has been to do
it through a hook to remain pure to the _gas.push architecture

But are hooks the appropriate tool to affect the environment outside of gas?
If not then using another mechanism is not impure

If an external mechanism is ok, then options include a qs parameter to the
_gas.js url if it is loaded in a script block or to the url of the script
that loads gas.js
The parameter is then extracted in gas.js or it's loading script and used
to determine if dc.js is to be used.

If hooks are indeed appropriate, then ga.js/dc.js will need to be loaded
within a hooked method

Thoughts?

## Brian Katz

Sr. Web Analyst, CWA
Vancouver, British Columbia (Pacific Time)
phone +1 778.374.3004 x224
web CardinalPath.com http://cpath.it/KuK2Gk

On Mon, Jul 22, 2013 at 10:05 AM, DarrenCarterMD
notifications@github.comwrote:

> I'd love to see a solution here, too, since I use dc.js so that I can
> build remarketing lists in Analytics. I don't want to lose that feature to
> use GAS.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/CardinalPath/gas/pull/33#issuecomment-21359286
> .

## 

Research shows that organizations with high online analytics maturityhttp://www.cardinalpath.com/services/online-analytics-maturity-model/assessment/?utm_source=footer&utm_medium=email&utm_campaign=cp-personal&utm_content=signatureget better ROI from their digital marketing and analytics investments. Not 
sure what your organization's analytics maturity is? Do you want to see how 
you compare to over 900 companies worldwide? Take the Online Analytics 
Maturity Assessment (OAMA)http://www.cardinalpath.com/services/online-analytics-maturity-model/assessment/?utm_source=footer&utm_medium=email&utm_campaign=cp-personal&utm_content=signatureand find out now!

 This email, including any attachments, is for the sole use of the intended 
recipient and may contain confidential information. If you are not the 
intended recipient, please immediately notify us by reply email or by 
telephone, delete this email and destroy any copies. Thank you

**Comment by tomfuertes** [comment]
@BrianKatz Kinda like the idea of a data-attribute/query-string approach. I'll try to take a shot at it later this week.

**Comment by tomfuertes** [comment]
Closing this PR in favor of #51

**Pull request closed without merging**
